import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>My Blog Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/black_bg_logo.png" />
      </Head>
      <main className="app">
        <Navbar />
      </main>
    </div>
  );
};

export default Home;
